In [1]:
import pandas as pd
data = pd.read_csv("carprices.csv")
data

                Car Model  Mileage  Sell Price($)  Age(yrs)
0                  BMW X5    69000          18000         6
1                  BMW X5    35000          34000         3
2                  BMW X5    57000          26100         5
3                  BMW X5    22500          40000         2
4                  BMW X5    46000          31500         4
5                 Audi A5    59000          29400         5
6                 Audi A5    52000          32000         5
7                 Audi A5    72000          19300         6
8                 Audi A5    91000          12000         8
9   Mercedez Benz C class    67000          22000         6
10  Mercedez Benz C class    83000          20000         7
11  Mercedez Benz C class    79000          21000         7
12  Mercedez Benz C class    59000          33000         5

In [2]:
dummies = pd.get_dummies(data['Car Model'])
dummies

    Audi A5  BMW X5  Mercedez Benz C class
0     False    True                  False
1     False    True                  False
2     False    True                  False
3     False    True                  False
4     False    True                  False
5      True   False                  False
6      True   False                  False
7      True   False                  False
8      True   False                  False
9     False   False                   True
10    False   False                   True
11    False   False                   True
12    False   False                   True

In [3]:
merged_data = pd.concat([data, dummies], axis = 'columns')
merged_data

,Car Model,Mileage,Sell Price($),Age(yrs),Audi A5,BMW X5,Mercedez Benz C class
0,BMW X5,69000,18000,6,False,True,False
1,BMW X5,35000,34000,3,False,True,False
2,BMW X5,57000,26100,5,False,True,False
3,BMW X5,22500,40000,2,False,True,False
4,BMW X5,46000,31500,4,False,True,False
5,Audi A5,59000,29400,5,True,False,False
6,Audi A5,52000,32000,5,True,False,False
7,Audi A5,72000,19300,6,True,False,False
8,Audi A5,91000,12000,8,True,False,False
9,Mercedez Benz C class,67000,22000,6,False,False,True
10,Mercedez Benz C class,83000,20000,7,False,False,True
11,Mercedez Benz C class,79000,21000,7,False,False,True
12,Mercedez Benz C class,59000,33000,5,False,False,True

In [5]:
final_data = merged_data.drop(['Car Model','Audi A5'],axis = 'columns')
final_data

    Mileage  Sell Price($)  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000          18000         6    True                  False
1     35000          34000         3    True                  False
2     57000          26100         5    True                  False
3     22500          40000         2    True                  False
4     46000          31500         4    True                  False
5     59000          29400         5   False                  False
6     52000          32000         5   False                  False
7     72000          19300         6   False                  False
8     91000          12000         8   False                  False
9     67000          22000         6   False                   True
10    83000          20000         7   False                   True
11    79000          21000         7   False                   True
12    59000          33000         5   False                   True

In [6]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [7]:
X = final_data.drop(['Sell Price($)'],axis = 'columns')
X

    Mileage  Age(yrs)  BMW X5  Mercedez Benz C class
0     69000         6    True                  False
1     35000         3    True                  False
2     57000         5    True                  False
3     22500         2    True                  False
4     46000         4    True                  False
5     59000         5   False                  False
6     52000         5   False                  False
7     72000         6   False                  False
8     91000         8   False                  False
9     67000         6   False                   True
10    83000         7   False                   True
11    79000         7   False                   True
12    59000         5   False                   True

In [8]:
Y = final_data['Sell Price($)']
Y

0     18000
1     34000
2     26100
3     40000
4     31500
5     29400
6     32000
7     19300
8     12000
9     22000
10    20000
11    21000
12    33000
Name: Sell Price($), dtype: int64

In [9]:
model.fit(X, Y)

LinearRegression()

In [12]:
model.predict([[45000,4,0,1]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([36991.31721061])

In [13]:
model.predict([[86000,7,1,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([11080.74313219])